# Generated by Django 5.1.1 on 2024-12-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
